apiVersion: v1
kind: Service
metadata:
  name: ingress-default-backend
  namespace: infrastructure
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ingress-default-backend

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-default-backend
  namespace: infrastructure
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-default-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi

      nodeSelector:
        k8s.info/application: infrastructure

      tolerations:
      - key: "application"
        operator: "Equal"
        value: "infrastructure"
        effect: "NoSchedule"
