apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "unit.name" . }}
    chart: {{ template "unit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service-selector: {{ .Release.Name }}
{{- with .Values.commonLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "unit.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  {{- if ne .Values.deploymentStrategy "RollingUpdate" }}
    rollingUpdate: null
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "unit.name" . }}
        release: {{ .Release.Name }}
        service-selector: {{ .Release.Name }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
{{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
{{- end }}
{{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
{{- end }}

      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
      - name: {{ template "unit.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.command }}
        command: {{ .Values.command }}
        {{- end }}
        {{- if .Values.args }}
        args: {{ .Values.args }}
        {{- end }}

{{- with .Values.env }}
        env:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.envCommon }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.envAdditional }}
{{ toYaml . | indent 8 }}
{{- end }}

{{- with .Values.ports }}
        ports:
{{ toYaml . | indent 8 }}
{{- end }}

{{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}

{{- with .Values.readinessProbe }}
        readinessProbe:
{{ toYaml . | indent 10 }}
{{- end }}

{{- with .Values.livenessProbe }}
        livenessProbe:
{{ toYaml . | indent 10 }}
{{- end }}

{{- with .Values.volumeMounts }}
        volumeMounts:
{{ toYaml . | indent 8 }}
{{- end }}

    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 6 }}
    {{- end }}


    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}


{{- with .Values.volumes }}
      volumes:
{{ toYaml . | indent 6 }}
{{- end }}

      restartPolicy: {{ .Values.restartPolicy }}
